# Generated by Django 5.1.5 on 2025-01-24 11:05

import autoslug.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0002_alter_brand_brand_image_alter_brand_slug'),
        ('category', '0004_categoryfieldvisibility'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Product name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Product Price')),
                ('product_description', models.TextField(blank=True, null=True, verbose_name='Product Description')),
                ('product_image', models.ImageField(blank=True, help_text='Upload an image for this product.', null=True, upload_to='products-images/', verbose_name='Product Image')),
                ('product_color', models.CharField(choices=[('Red', 'Red'), ('Blue', 'Blue'), ('Green', 'Green'), ('Yellow', 'Yellow'), ('Black', 'Black'), ('White', 'White'), ('Other', 'Other')], default='Black', max_length=100, verbose_name='Product Color')),
                ('size', models.CharField(blank=True, max_length=50, null=True, verbose_name='Product Size')),
                ('stock_quantity', models.PositiveIntegerField(default=0, help_text='The number of units available in stock.', verbose_name='Stock Quantity')),
                ('is_active', models.BooleanField(default=True, help_text='Tick to make the product available for sale.', verbose_name='Is Active')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='brands.brand', verbose_name='Brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category', verbose_name='Category')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.subcategory', verbose_name='Sub-Category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='product-images/', verbose_name='Product Image')),
                ('image_type', models.CharField(choices=[('main', 'Main Image'), ('gallery', 'Gallery Image'), ('zoom', 'Zoom Image')], default='main', max_length=10, verbose_name='Image Type')),
                ('alt_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Alt Text')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='image', unique=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='products.product')),
            ],
            options={
                'verbose_name': 'Product Image',
                'verbose_name_plural': 'Product Images',
                'constraints': [models.UniqueConstraint(condition=models.Q(('image_type', 'main')), fields=('product', 'image_type'), name='unique_main_image')],
            },
        ),
    ]
