# Generated by Django 5.1.5 on 2025-01-24 11:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_delete_categoryfieldvisibility'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AddField(
            model_name='product',
            name='is_shipping_required',
            field=models.BooleanField(default=True, help_text='Tick if this product needs shipping or not.', verbose_name='Is Shipping Required'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_dimension',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='Product Dimension'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='product_weight',
            field=models.DecimalField(decimal_places=2, default=12.2, max_digits=10, verbose_name='Product Weight'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='product',
            name='sub_category',
        ),
        migrations.AddField(
            model_name='product',
            name='sub_category',
            field=models.ManyToManyField(to='category.subcategory', verbose_name='Sub-Category'),
        ),
    ]
