# Generated by Django 5.1.5 on 2025-01-24 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_options_product_is_shipping_required_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_dimension',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Product Dimension'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Product Weight'),
        ),
    ]
