# Generated by Django 5.1.5 on 2025-01-24 11:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_delete_categoryfieldvisibility'),
        ('products', '0003_alter_product_product_dimension_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sub_category',
        ),
        migrations.AddField(
            model_name='product',
            name='sub_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='category.subcategory', verbose_name='Sub-Category'),
            preserve_default=False,
        ),
    ]
