# Generated by Django 5.1.5 on 2025-01-24 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_sub_category_product_sub_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_shipping_required',
        ),
        migrations.AddField(
            model_name='product',
            name='is_digital',
            field=models.BooleanField(default=True, help_text='Tick if this product needs shipping or not.', verbose_name='Is Product digital'),
        ),
    ]
