# Generated by Django 5.1.5 on 2025-01-24 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_is_digital_alter_product_is_trending'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image_alt_1',
            field=models.ImageField(blank=True, help_text='Upload an image for this product.', null=True, upload_to='products-images/', verbose_name='Product Image Alt 1'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_image_alt_2',
            field=models.ImageField(blank=True, help_text='Upload an image for this product.', null=True, upload_to='products-images/', verbose_name='Product Image Alt 2'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_image_alt_3',
            field=models.ImageField(blank=True, help_text='Upload an image for this product.', null=True, upload_to='products-images/', verbose_name='Product Image Alt 3'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_image_alt_4',
            field=models.ImageField(blank=True, help_text='Upload an image for this product.', null=True, upload_to='products-images/', verbose_name='Product Image Alt 4'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image_type',
            field=models.CharField(choices=[('main', 'Main Image'), ('gallery', 'Gallery Image')], default='main', max_length=10, verbose_name='Image Type'),
        ),
    ]
