# Generated by Django 5.1.5 on 2025-01-24 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_product_discount_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_special_offer',
            field=models.BooleanField(default=False, help_text='Tick if this product is a special offer.', verbose_name='Is Special Offer'),
        ),
    ]
