# Generated by Django 5.1.5 on 2025-01-25 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_is_special_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_trending',
            field=models.BooleanField(default=False, help_text='Tick if this product is a trending product.', verbose_name='Is Trending'),
        ),
    ]
