# Generated by Django 5.1.5 on 2025-01-24 11:05

import autoslug.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_alter_category_slug_alter_subcategory_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryFieldVisibility',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('show_size', models.BooleanField(default=False, verbose_name='Show Size Field')),
                ('show_color', models.BooleanField(default=True, verbose_name='Show Color Field')),
                ('show_stock_quantity', models.BooleanField(default=True, verbose_name='Show Stock Quantity Field')),
                ('show_brand', models.BooleanField(default=True, verbose_name='Show Brand Field')),
                ('show_weight', models.BooleanField(default=True, verbose_name='Show Weight Field')),
                ('show_dimension', models.BooleanField(default=False, verbose_name='Show Dimension Field')),
                ('show_material', models.BooleanField(default=False, verbose_name='Show Material Field')),
                ('show_description', models.BooleanField(default=True, verbose_name='Show Description Field')),
                ('show_warranty', models.BooleanField(default=False, verbose_name='Show Warranty Field')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='category', unique=True)),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='category_field_visibility', to='category.category')),
            ],
            options={
                'verbose_name': 'Category Field Visibility',
                'verbose_name_plural': 'Category Field Visibilities',
                'ordering': ['-created_at'],
            },
        ),
    ]
