# Generated by Django 5.1.5 on 2025-01-24 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_categoryfieldvisibility'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoryFieldVisibility',
        ),
    ]
